import csv
import io

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse

from app.config import SUPABASE_CONFIGURED
from app.db import get_supabase
from app.auth import get_current_user
from app.pdf import build_pdf
from app.mock_data import (
    BRSR_PRINCIPLES, BRSR_CATEGORY_SCORES, CBAM_SHIPMENTS, COMPANY,
    KPIS, SCOPE_BREAKDOWN, FACILITY_EMISSIONS, EMISSIONS_TREND,
    log_activity,
)

router = APIRouter(prefix="/api/reports", tags=["reports"])


def _brsr_completeness() -> int:
    return round(sum(p["completeness"] for p in BRSR_PRINCIPLES) / len(BRSR_PRINCIPLES))


# ---- BRSR ----

@router.get("/brsr")
def get_brsr(user: dict = Depends(get_current_user)):
    if SUPABASE_CONFIGURED:
        sb = get_supabase()
        result = sb.table("brsr_reports").select("*").eq("company_id", user["company_id"]).execute()
        if result.data:
            return result.data[0]
    return {
        "company": COMPANY,
        "categoryScores": BRSR_CATEGORY_SCORES,
        "principles": BRSR_PRINCIPLES,
        "completeness": _brsr_completeness(),
        "status": "draft",
    }


@router.post("/brsr/generate")
def generate_brsr(user: dict = Depends(get_current_user)):
    completeness = _brsr_completeness()
    record = {
        "company_id": user["company_id"],
        "status": "generated",
        "completeness": completeness,
        "principles": BRSR_PRINCIPLES,
        "category_scores": BRSR_CATEGORY_SCORES,
    }
    if SUPABASE_CONFIGURED:
        sb = get_supabase()
        result = sb.table("brsr_reports").upsert(record, on_conflict="company_id").execute()
        generated = result.data[0]
    else:
        generated = record
    log_activity("BRSR report regenerated (Section C principle data refreshed)")
    return generated


@router.get("/brsr/export")
def export_brsr(user: dict = Depends(get_current_user)):
    """Real PDF download (content-disposition attachment)."""
    sections = [
        ("Section A — General Disclosures", [
            f"Legal name: {COMPANY['name']}",
            f"CIN / GSTIN: {COMPANY['gstin']}",
            f"Sector: {COMPANY['sector']}",
            f"Registered office: {COMPANY['location']}",
            f"Employees: {COMPANY['employees']} (378 permanent, 34 contractual)",
            f"Turnover (FY25-26): Rs. {COMPANY['turnover_cr']} Cr",
            "Listing status: Unlisted — top supplier disclosure",
        ]),
        ("Section B — Management & Process", [
            "Sustainability oversight sits with a Board-level ESG committee that meets quarterly.",
            "Policies covering environment, labor and human rights are reviewed annually and",
            "published on the company's investor relations page. Grievance redressal is available",
            "to employees, suppliers and local communities via a dedicated channel.",
        ]),
        ("Section C — Principle-wise Performance", [
            f"{p['id']}. {p['title']}: {p['completeness']}% complete"
            for p in BRSR_PRINCIPLES
        ]),
        ("Category Scores", [
            f"{c['category']}: {c['score']}%" for c in BRSR_CATEGORY_SCORES
        ]),
        ("Emissions Summary (12 months)", [
            f"{m['month']}: Scope 1 {m['scope1']} tCO2e, Scope 2 {m['scope2']} tCO2e, Scope 3 {m['scope3']} tCO2e"
            for m in EMISSIONS_TREND
        ]),
        ("Scope & Facility Breakdown (current period)", [
            *(f"{s['name']}: {s['value']} tCO2e" for s in SCOPE_BREAKDOWN),
            "",
            *(f"{f['facility']}: {f['emissions']} tCO2e" for f in FACILITY_EMISSIONS),
        ]),
        ("Compliance Snapshot", [
            f"Overall compliance score: {KPIS['complianceScore']}%",
            f"Open risk flags: {KPIS['riskFlags']}",
            f"Reports due: {KPIS['reportsDue']} ({KPIS['nextDeadline']})",
        ]),
    ]
    pdf = build_pdf(
        "BRSR Annual Report FY25-26",
        f"{COMPANY['name']} - generated by GreenComply",
        sections,
    )
    log_activity("BRSR Annual Report PDF exported")
    return StreamingResponse(
        iter([pdf]),
        media_type="application/pdf",
        headers={"Content-Disposition": 'attachment; filename="BRSR_Annual_Report_FY25-26.pdf"'},
    )


# ---- CBAM ----

def _normalise_shipment(s: dict) -> dict:
    return {
        "id": s.get("id") or s.get("shipment_ref"),
        "product": s.get("product"),
        "tonnes": s.get("tonnes"),
        "emissionsPerTonne": s.get("emissionsPerTonne") or s.get("emissions_per_tonne"),
        "carbonCost": s.get("carbonCost") or s.get("carbon_cost"),
        "status": s.get("status"),
        "declarationDue": s.get("declarationDue") or s.get("declaration_due"),
    }


@router.get("/cbam")
def get_cbam(user: dict = Depends(get_current_user)):
    if SUPABASE_CONFIGURED:
        sb = get_supabase()
        result = sb.table("cbam_declarations").select("*").eq("company_id", user["company_id"]).order("shipment_ref").execute()
        return [_normalise_shipment(s) for s in result.data]
    return [_normalise_shipment(s) for s in CBAM_SHIPMENTS]


@router.post("/cbam/generate")
def generate_cbam(user: dict = Depends(get_current_user)):
    total_cost = sum(s["carbonCost"] for s in CBAM_SHIPMENTS)
    total_tonnes = sum(s["tonnes"] for s in CBAM_SHIPMENTS)
    record = {"company_id": user["company_id"], "shipments": CBAM_SHIPMENTS, "totalCost": total_cost, "totalTonnes": total_tonnes}
    log_activity("CBAM Q3 declaration regenerated from shipment ledger")
    if SUPABASE_CONFIGURED:
        sb = get_supabase()
        result = sb.table("cbam_declarations").select("*").eq("company_id", user["company_id"]).execute()
        shipments = [_normalise_shipment(s) for s in result.data]
        return {
            "company_id": user["company_id"],
            "shipments": shipments,
            "totalCost": sum(s["carbonCost"] or 0 for s in shipments),
            "totalTonnes": sum(s["tonnes"] or 0 for s in shipments),
        }
    return record


@router.get("/cbam/export")
def export_cbam(user: dict = Depends(get_current_user)):
    """Real CSV download in a CBAM-declaration-compatible column layout."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "shipment_id", "goods_description", "net_mass_tonnes",
        "embedded_emissions_tco2e_per_tonne", "carbon_cost_eur",
        "declaration_due", "status",
    ])
    for s in CBAM_SHIPMENTS:
        writer.writerow([
            s["id"], s["product"], s["tonnes"], s["emissionsPerTonne"],
            s["carbonCost"], s["declarationDue"], s["status"],
        ])
    writer.writerow([])
    writer.writerow(["TOTAL", "", sum(s["tonnes"] for s in CBAM_SHIPMENTS), "", sum(s["carbonCost"] for s in CBAM_SHIPMENTS), "", ""])
    log_activity("CBAM Q3 declaration CSV exported")
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="CBAM_Declaration_Q3_2026.csv"'},
    )
